/* Connect AI — sample data (GCC / Saudi context) */

const C = (h) => `oklch(0.62 0.15 ${h})`;

const departments = [
  { id: "eng", en: "Engineering", ar: "الهندسة" },
  { id: "prod", en: "Product", ar: "المنتجات" },
  { id: "data", en: "Data & AI", ar: "البيانات والذكاء" },
  { id: "fin", en: "Finance", ar: "المالية" },
  { id: "mkt", en: "Marketing", ar: "التسويق" },
  { id: "ops", en: "Operations", ar: "العمليات" },
  { id: "hr", en: "People", ar: "الموارد البشرية" },
];

const stages = [
  { id: "applied", color: "var(--text-3)" },
  { id: "screening", color: "var(--info)" },
  { id: "assessment", color: "var(--purple)" },
  { id: "aiInterview", color: "var(--ai)" },
  { id: "hrInterview", color: "var(--accent)" },
  { id: "techInterview", color: "var(--accent)" },
  { id: "offer", color: "var(--warning)" },
  { id: "hired", color: "var(--success)" },
];

const jobs = [
  { id: "j1", en: "Senior Product Manager", ar: "مدير منتجات أول", dept: "prod", loc: { en: "Riyadh", ar: "الرياض" }, type: { en: "Full-time", ar: "دوام كامل" }, grade: "M3", openings: 2, status: "open", posted: 12, applicants: 86, mgr: { en: "Faisal Al-Otaibi", ar: "فيصل العتيبي" }, salary: "28,000 – 36,000", top: "assessment" },
  { id: "j2", en: "Senior Frontend Engineer", ar: "مهندس واجهات أول", dept: "eng", loc: { en: "Riyadh", ar: "الرياض" }, type: { en: "Full-time", ar: "دوام كامل" }, grade: "E4", openings: 3, status: "open", posted: 8, applicants: 142, mgr: { en: "Noura Al-Qahtani", ar: "نورة القحطاني" }, salary: "24,000 – 32,000", top: "techInterview" },
  { id: "j3", en: "Data Scientist", ar: "عالم بيانات", dept: "data", loc: { en: "Jeddah", ar: "جدة" }, type: { en: "Full-time", ar: "دوام كامل" }, grade: "E4", openings: 1, status: "open", posted: 5, applicants: 64, mgr: { en: "Tariq Al-Harbi", ar: "طارق الحربي" }, salary: "26,000 – 34,000", top: "aiInterview" },
  { id: "j4", en: "Financial Analyst", ar: "محلل مالي", dept: "fin", loc: { en: "Riyadh", ar: "الرياض" }, type: { en: "Full-time", ar: "دوام كامل" }, grade: "E2", openings: 2, status: "closing", posted: 21, applicants: 98, mgr: { en: "Hanan Al-Dossari", ar: "حنان الدوسري" }, salary: "16,000 – 22,000", top: "offer" },
  { id: "j5", en: "Growth Marketing Lead", ar: "قائد تسويق النمو", dept: "mkt", loc: { en: "Dubai", ar: "دبي" }, type: { en: "Full-time", ar: "دوام كامل" }, grade: "M2", openings: 1, status: "open", posted: 3, applicants: 41, mgr: { en: "Salem Al-Ghamdi", ar: "سالم الغامدي" }, salary: "22,000 – 30,000", top: "screening" },
  { id: "j6", en: "DevOps Engineer", ar: "مهندس DevOps", dept: "eng", loc: { en: "Remote – KSA", ar: "عن بُعد – السعودية" }, type: { en: "Full-time", ar: "دوام كامل" }, grade: "E3", openings: 2, status: "open", posted: 15, applicants: 73, mgr: { en: "Noura Al-Qahtani", ar: "نورة القحطاني" }, salary: "20,000 – 28,000", top: "applied" },
  { id: "j7", en: "UX Researcher", ar: "باحث تجربة المستخدم", dept: "prod", loc: { en: "Riyadh", ar: "الرياض" }, type: { en: "Contract", ar: "عقد" }, grade: "E3", openings: 1, status: "draft", posted: 0, applicants: 0, mgr: { en: "Faisal Al-Otaibi", ar: "فيصل العتيبي" }, salary: "18,000 – 24,000", top: "applied" },
  { id: "j8", en: "HR Business Partner", ar: "شريك أعمال الموارد البشرية", dept: "hr", loc: { en: "Dammam", ar: "الدمام" }, type: { en: "Full-time", ar: "دوام كامل" }, grade: "M2", openings: 1, status: "onhold", posted: 30, applicants: 55, mgr: { en: "Maha Al-Shehri", ar: "مها الشهري" }, salary: "19,000 – 26,000", top: "hrInterview" },
];

// Candidate factory
let cid = 0;
function cand(o) {
  cid++;
  return Object.assign({ id: "c" + cid }, o);
}

const candidates = [
  cand({
    name: { en: "Abdulrahman Al-Saud", ar: "عبدالرحمن آل سعود" }, initials: "ع", avatar: C(265),
    title: { en: "Product Manager · STC Pay", ar: "مدير منتجات · STC Pay" },
    job: "j1", stage: "aiInterview", match: 94, exp: 8, applied: 6,
    loc: { en: "Riyadh, KSA", ar: "الرياض، السعودية" }, email: "a.alsaud@example.com", phone: "+966 50 112 3344",
    edu: { en: "MBA, KFUPM · BSc Computer Science, KSU", ar: "ماجستير إدارة أعمال، جامعة الملك فهد · بكالوريوس علوم حاسب، جامعة الملك سعود" },
    skills: ["Product Strategy", "Fintech", "Agile", "Roadmapping", "SQL", "Stakeholder Mgmt", "A/B Testing"],
    missing: ["Mobile growth", "ML products"],
    langs: [{ en: "Arabic", ar: "العربية", lvl: "Native" }, { en: "English", ar: "الإنجليزية", lvl: "Fluent" }],
    certs: ["Pragmatic PM", "SAFe PO/PM", "Google Analytics"],
    factors: { skills: 96, experience: 92, education: 90, industry: 98, certs: 88, language: 95 },
    assess: 91, video: 89, percentile: 96, source: { en: "LinkedIn", ar: "لينكدإن" },
    summary: { en: "Highly recommended candidate with 8 years of fintech product leadership at STC Pay and Geidea. Strong on payments strategy and stakeholder alignment; excellent bilingual communication. Minor gap in ML-driven product experience.", ar: "مرشح يُوصى به بشدة بخبرة 8 سنوات في قيادة منتجات التقنية المالية لدى STC Pay وجيديا. قوي في استراتيجية المدفوعات ومواءمة أصحاب المصلحة؛ تواصل ثنائي اللغة ممتاز. فجوة بسيطة في خبرة منتجات تعلّم الآلة." },
  }),
  cand({
    name: { en: "Sara Al-Mutairi", ar: "سارة المطيري" }, initials: "س", avatar: C(20),
    title: { en: "Senior PM · Jahez", ar: "مدير منتجات أول · جاهز" },
    job: "j1", stage: "assessment", match: 90, exp: 7, applied: 9,
    loc: { en: "Riyadh, KSA", ar: "الرياض، السعودية" }, email: "s.almutairi@example.com", phone: "+966 55 220 7788",
    edu: { en: "BSc Industrial Engineering, KAU", ar: "بكالوريوس هندسة صناعية، جامعة الملك عبدالعزيز" },
    skills: ["Product Discovery", "Marketplaces", "Data Analysis", "Figma", "OKRs", "User Research"],
    missing: ["Payments", "B2B SaaS"],
    langs: [{ en: "Arabic", ar: "العربية", lvl: "Native" }, { en: "English", ar: "الإنجليزية", lvl: "Fluent" }],
    certs: ["Reforge PM", "Scrum PSPO I"],
    factors: { skills: 91, experience: 86, education: 88, industry: 84, certs: 82, language: 94 },
    assess: 88, video: 85, percentile: 91, source: { en: "Bayt", ar: "بيت.كوم" },
    summary: { en: "Strong marketplace PM from Jahez with sharp discovery and analytics skills. Excellent assessment performance. Best suited for consumer-facing roles; lighter on payments domain.", ar: "مديرة منتجات قوية في الأسواق الإلكترونية من جاهز بمهارات اكتشاف وتحليلات ممتازة. أداء تقييم متميّز. الأنسب للأدوار الموجهة للمستهلك؛ خبرة أقل في مجال المدفوعات." },
  }),
  cand({
    name: { en: "Omar Khalil", ar: "عمر خليل" }, initials: "O", avatar: C(150),
    title: { en: "Product Lead · Careem", ar: "قائد منتجات · كريم" },
    job: "j1", stage: "screening", match: 87, exp: 9, applied: 4,
    loc: { en: "Dubai, UAE", ar: "دبي، الإمارات" }, email: "o.khalil@example.com", phone: "+971 50 661 2200",
    edu: { en: "MSc Computer Science, AUB", ar: "ماجستير علوم حاسب، الجامعة الأمريكية في بيروت" },
    skills: ["Platform PM", "APIs", "Growth", "Experimentation", "SQL", "Strategy"],
    missing: ["Arabic-first products"],
    langs: [{ en: "Arabic", ar: "العربية", lvl: "Conversational" }, { en: "English", ar: "الإنجليزية", lvl: "Native" }],
    certs: ["Mind the Product", "AWS CP"],
    factors: { skills: 89, experience: 94, education: 86, industry: 82, certs: 78, language: 80 },
    assess: 0, video: 0, percentile: 84, source: { en: "Referral", ar: "ترشيح" },
    summary: { en: "Seasoned platform PM from Careem with deep growth and experimentation background. Strong technical fluency. Relocation from UAE required; Arabic is conversational.", ar: "مدير منتجات منصات متمرّس من كريم بخلفية عميقة في النمو والتجارب. طلاقة تقنية عالية. يتطلب الانتقال من الإمارات؛ العربية بمستوى محادثة." },
  }),
  cand({
    name: { en: "Lina Haddad", ar: "لينا حداد" }, initials: "L", avatar: C(330),
    title: { en: "Group PM · Noon", ar: "مدير منتجات مجموعة · نون" },
    job: "j1", stage: "applied", match: 82, exp: 10, applied: 1,
    loc: { en: "Riyadh, KSA", ar: "الرياض، السعودية" }, email: "l.haddad@example.com", phone: "+966 53 778 9911",
    edu: { en: "MBA INSEAD · BSc CS", ar: "ماجستير إدارة أعمال إنسياد · بكالوريوس علوم حاسب" },
    skills: ["E-commerce", "Team Leadership", "Roadmapping", "Vision", "Hiring"],
    missing: ["Hands-on analytics", "Fintech"],
    langs: [{ en: "Arabic", ar: "العربية", lvl: "Fluent" }, { en: "English", ar: "الإنجليزية", lvl: "Fluent" }],
    certs: ["INSEAD Exec"],
    factors: { skills: 84, experience: 95, education: 92, industry: 80, certs: 70, language: 90 },
    assess: 0, video: 0, percentile: 79, source: { en: "Career Portal", ar: "بوابة التوظيف" },
    summary: { en: "Senior leader with broad e-commerce scope at Noon. Excellent for a people-leadership track. Slightly senior for the IC scope of this requisition.", ar: "قائدة كبيرة بنطاق واسع في التجارة الإلكترونية لدى نون. ممتازة لمسار قيادة الفرق. أقدم قليلاً من نطاق هذه الوظيفة الفردية." },
  }),
  cand({
    name: { en: "Yousef Al-Rashid", ar: "يوسف الراشد" }, initials: "ي", avatar: C(245),
    title: { en: "Frontend Engineer · Tamara", ar: "مهندس واجهات · تمارا" },
    job: "j2", stage: "techInterview", match: 92, exp: 6, applied: 7,
    loc: { en: "Riyadh, KSA", ar: "الرياض، السعودية" }, email: "y.rashid@example.com", phone: "+966 56 334 1100",
    edu: { en: "BSc Software Engineering, KSU", ar: "بكالوريوس هندسة برمجيات، جامعة الملك سعود" },
    skills: ["React", "TypeScript", "Next.js", "Design Systems", "Performance", "RTL/i18n", "Testing"],
    missing: ["Mobile (RN)"],
    langs: [{ en: "Arabic", ar: "العربية", lvl: "Native" }, { en: "English", ar: "الإنجليزية", lvl: "Fluent" }],
    certs: ["Meta Frontend", "AWS Dev Assoc"],
    factors: { skills: 95, experience: 88, education: 86, industry: 90, certs: 84, language: 92 },
    assess: 94, video: 90, percentile: 95, source: { en: "LinkedIn", ar: "لينكدإن" },
    summary: { en: "Top-tier frontend engineer from Tamara with exceptional React/TypeScript depth and strong RTL/i18n experience — directly relevant to bilingual products. Highest assessment score in the pool.", ar: "مهندس واجهات من الطراز الأول من تمارا بعمق استثنائي في React/TypeScript وخبرة قوية في RTL والتعدد اللغوي — وثيق الصلة بالمنتجات ثنائية اللغة. أعلى نتيجة تقييم في المجموعة." },
  }),
  cand({
    name: { en: "Maryam Al-Balushi", ar: "مريم البلوشي" }, initials: "م", avatar: C(190),
    title: { en: "Frontend Engineer · Mrsool", ar: "مهندسة واجهات · مرسول" },
    job: "j2", stage: "assessment", match: 86, exp: 5, applied: 5,
    loc: { en: "Jeddah, KSA", ar: "جدة، السعودية" }, email: "m.balushi@example.com", phone: "+966 59 880 6677",
    edu: { en: "BSc Computer Science, Effat University", ar: "بكالوريوس علوم حاسب، جامعة عفت" },
    skills: ["React", "Vue", "CSS Architecture", "Accessibility", "Jest", "Figma"],
    missing: ["TypeScript depth", "SSR"],
    langs: [{ en: "Arabic", ar: "العربية", lvl: "Native" }, { en: "English", ar: "الإنجليزية", lvl: "Fluent" }],
    certs: ["Google UX", "freeCodeCamp"],
    factors: { skills: 88, experience: 80, education: 85, industry: 86, certs: 76, language: 90 },
    assess: 83, video: 0, percentile: 82, source: { en: "Indeed", ar: "إنديد" },
    summary: { en: "Promising frontend engineer with strong accessibility and design sensibility. Solid assessment. Would benefit from deeper TypeScript and SSR exposure for this senior role.", ar: "مهندسة واجهات واعدة بحس قوي في إتاحة الوصول والتصميم. تقييم جيد. ستستفيد من خبرة أعمق في TypeScript والعرض من الخادم لهذا الدور الأول." },
  }),
  cand({
    name: { en: "Khalid Al-Anazi", ar: "خالد العنزي" }, initials: "خ", avatar: C(60),
    title: { en: "Software Engineer · Lean", ar: "مهندس برمجيات · لين" },
    job: "j2", stage: "screening", match: 79, exp: 4, applied: 3,
    loc: { en: "Riyadh, KSA", ar: "الرياض، السعودية" }, email: "k.anazi@example.com", phone: "+966 50 445 2233",
    edu: { en: "BSc Information Systems, IMSIU", ar: "بكالوريوس نظم معلومات، جامعة الإمام" },
    skills: ["JavaScript", "React", "Node.js", "REST", "Git"],
    missing: ["Design systems", "Performance", "TypeScript"],
    langs: [{ en: "Arabic", ar: "العربية", lvl: "Native" }, { en: "English", ar: "الإنجليزية", lvl: "Intermediate" }],
    certs: ["Udacity FE Nanodegree"],
    factors: { skills: 78, experience: 72, education: 82, industry: 80, certs: 68, language: 74 },
    assess: 0, video: 0, percentile: 68, source: { en: "Career Portal", ar: "بوابة التوظيف" },
    summary: { en: "Mid-level engineer with solid fundamentals and fintech exposure at Lean. Below the seniority bar for this requisition but a strong fit for an E3 backfill.", ar: "مهندس متوسط المستوى بأساسيات متينة وخبرة في التقنية المالية لدى لين. أقل من مستوى الأقدمية لهذه الوظيفة لكنه مناسب جداً لشاغر بدرجة E3." },
  }),
  cand({
    name: { en: "Aisha Al-Zahrani", ar: "عائشة الزهراني" }, initials: "ع", avatar: C(295),
    title: { en: "ML Engineer · Mozn", ar: "مهندسة تعلم آلة · موزن" },
    job: "j3", stage: "aiInterview", match: 93, exp: 6, applied: 4,
    loc: { en: "Jeddah, KSA", ar: "جدة، السعودية" }, email: "a.zahrani@example.com", phone: "+966 54 909 1122",
    edu: { en: "MSc Machine Learning, KAUST", ar: "ماجستير تعلّم الآلة، جامعة الملك عبدالله (كاوست)" },
    skills: ["Python", "PyTorch", "NLP", "Arabic NLP", "MLOps", "SQL", "Statistics"],
    missing: ["Large-scale serving"],
    langs: [{ en: "Arabic", ar: "العربية", lvl: "Native" }, { en: "English", ar: "الإنجليزية", lvl: "Fluent" }],
    certs: ["DeepLearning.AI", "TensorFlow Dev"],
    factors: { skills: 95, experience: 86, education: 96, industry: 90, certs: 90, language: 92 },
    assess: 92, video: 91, percentile: 97, source: { en: "Referral", ar: "ترشيح" },
    summary: { en: "Exceptional ML engineer from KAUST with rare Arabic-NLP specialization — strategically valuable. Outstanding assessment and interview scores. Strongest candidate for the Data Scientist role.", ar: "مهندسة تعلّم آلة استثنائية من كاوست بتخصص نادر في معالجة اللغة العربية — قيمة استراتيجية. نتائج تقييم ومقابلة متميزة. أقوى مرشحة لوظيفة عالم البيانات." },
  }),
  cand({
    name: { en: "Hassan Al-Najjar", ar: "حسن النجار" }, initials: "ح", avatar: C(120),
    title: { en: "Data Analyst · stc", ar: "محلل بيانات · stc" },
    job: "j3", stage: "applied", match: 80, exp: 5, applied: 2,
    loc: { en: "Riyadh, KSA", ar: "الرياض، السعودية" }, email: "h.najjar@example.com", phone: "+966 57 332 8800",
    edu: { en: "BSc Statistics, KSU", ar: "بكالوريوس إحصاء، جامعة الملك سعود" },
    skills: ["SQL", "Power BI", "Python", "ETL", "A/B Testing"],
    missing: ["Deep learning", "MLOps", "Research"],
    langs: [{ en: "Arabic", ar: "العربية", lvl: "Native" }, { en: "English", ar: "الإنجليزية", lvl: "Fluent" }],
    certs: ["Microsoft DA", "Google Data Analytics"],
    factors: { skills: 80, experience: 78, education: 82, industry: 84, certs: 80, language: 88 },
    assess: 0, video: 0, percentile: 70, source: { en: "LinkedIn", ar: "لينكدإن" },
    summary: { en: "Strong analytics generalist from stc with good BI and SQL. Lighter on ML research depth required for a Data Scientist track.", ar: "محلل بيانات عام قوي من stc بمهارات جيدة في ذكاء الأعمال وSQL. خبرة أقل في عمق أبحاث تعلّم الآلة المطلوبة لمسار عالم البيانات." },
  }),
  cand({
    name: { en: "Fatima Al-Shamsi", ar: "فاطمة الشامسي" }, initials: "ف", avatar: C(10),
    title: { en: "Senior Financial Analyst · ACWA Power", ar: "محللة مالية أولى · أكوا باور" },
    job: "j4", stage: "offer", match: 91, exp: 7, applied: 18,
    loc: { en: "Riyadh, KSA", ar: "الرياض، السعودية" }, email: "f.shamsi@example.com", phone: "+966 55 667 3322",
    edu: { en: "BSc Finance, KFUPM · CFA Level III", ar: "بكالوريوس مالية، جامعة الملك فهد · CFA المستوى الثالث" },
    skills: ["Financial Modeling", "Valuation", "IFRS", "Power BI", "Forecasting", "M&A"],
    missing: ["Treasury"],
    langs: [{ en: "Arabic", ar: "العربية", lvl: "Native" }, { en: "English", ar: "الإنجليزية", lvl: "Fluent" }],
    certs: ["CFA III Candidate", "FMVA"],
    factors: { skills: 93, experience: 90, education: 92, industry: 94, certs: 95, language: 90 },
    assess: 90, video: 88, percentile: 94, source: { en: "Referral", ar: "ترشيح" },
    summary: { en: "Excellent finance candidate from ACWA Power with strong modeling and IFRS depth and CFA progress. Cleared all interviews — offer in progress.", ar: "مرشحة مالية ممتازة من أكوا باور بعمق قوي في النمذجة ومعايير IFRS وتقدم في CFA. اجتازت جميع المقابلات — العرض قيد الإعداد." },
  }),
  cand({
    name: { en: "Mohammed Al-Dosari", ar: "محمد الدوسري" }, initials: "م", avatar: C(85),
    title: { en: "Performance Marketer · Hungerstation", ar: "مسوّق أداء · هنقرستيشن" },
    job: "j5", stage: "screening", match: 84, exp: 6, applied: 2,
    loc: { en: "Dubai, UAE", ar: "دبي، الإمارات" }, email: "m.dosari@example.com", phone: "+971 52 778 9090",
    edu: { en: "BBA Marketing, GUST", ar: "بكالوريوس إدارة أعمال تسويق، جامعة الخليج" },
    skills: ["Paid Social", "SEO", "CRM", "Analytics", "Growth Loops", "Arabic copy"],
    missing: ["Brand", "B2B"],
    langs: [{ en: "Arabic", ar: "العربية", lvl: "Native" }, { en: "English", ar: "الإنجليزية", lvl: "Fluent" }],
    certs: ["Google Ads", "Meta Blueprint"],
    factors: { skills: 86, experience: 82, education: 80, industry: 88, certs: 84, language: 90 },
    assess: 0, video: 0, percentile: 78, source: { en: "LinkedIn", ar: "لينكدإن" },
    summary: { en: "Performance-focused growth marketer with strong paid acquisition track record at Hungerstation. Solid bilingual copy. Less brand/B2B exposure.", ar: "مسوّق نمو يركز على الأداء بسجل قوي في الاستحواذ المدفوع لدى هنقرستيشن. كتابة ثنائية اللغة جيدة. خبرة أقل في العلامة التجارية وقطاع B2B." },
  }),
];

// Pipeline = candidates for currently-viewed job (default j1 + j2 mix for richness)
export const DATA = {
  departments, stages, jobs, candidates,
  employmentTypes: [
    { en: "Full-time", ar: "دوام كامل" }, { en: "Part-time", ar: "دوام جزئي" },
    { en: "Contract", ar: "عقد" }, { en: "Internship", ar: "تدريب" },
  ],
  grades: ["E2", "E3", "E4", "M2", "M3", "M4"],
  locations: [
    { en: "Riyadh", ar: "الرياض" }, { en: "Jeddah", ar: "جدة" }, { en: "Dammam", ar: "الدمام" },
    { en: "Dubai", ar: "دبي" }, { en: "Remote – KSA", ar: "عن بُعد – السعودية" },
  ],
};

window.DATA = DATA;
