import type { Department, Job, Candidate, Workflow, WorkflowStage, EmailTemplate, MatchFactors, CandidateLang } from '@/types'

const C = (h: number) => `oklch(0.62 0.15 ${h})`

export const departments: Department[] = [
  { id: 'eng', nameEn: 'Engineering', nameAr: 'الهندسة' },
  { id: 'prod', nameEn: 'Product', nameAr: 'المنتجات' },
  { id: 'data', nameEn: 'Data & AI', nameAr: 'البيانات والذكاء' },
  { id: 'fin', nameEn: 'Finance', nameAr: 'المالية' },
  { id: 'mkt', nameEn: 'Marketing', nameAr: 'التسويق' },
  { id: 'ops', nameEn: 'Operations', nameAr: 'العمليات' },
  { id: 'hr', nameEn: 'People', nameAr: 'الموارد البشرية' },
]

export const jobs: Job[] = [
  { id: 'j1', titleEn: 'Senior Product Manager', titleAr: 'مدير منتجات أول', deptId: 'prod', locEn: 'Riyadh', locAr: 'الرياض', typeEn: 'Full-time', typeAr: 'دوام كامل', grade: 'M3', openings: 2, status: 'open', posted: 12, applicants: 86, mgrEn: 'Faisal Al-Otaibi', mgrAr: 'فيصل العتيبي', salary: '28,000 – 36,000', topStage: 'assessment' },
  { id: 'j2', titleEn: 'Senior Frontend Engineer', titleAr: 'مهندس واجهات أول', deptId: 'eng', locEn: 'Riyadh', locAr: 'الرياض', typeEn: 'Full-time', typeAr: 'دوام كامل', grade: 'E4', openings: 3, status: 'open', posted: 8, applicants: 142, mgrEn: 'Noura Al-Qahtani', mgrAr: 'نورة القحطاني', salary: '24,000 – 32,000', topStage: 'techInterview' },
  { id: 'j3', titleEn: 'Data Scientist', titleAr: 'عالم بيانات', deptId: 'data', locEn: 'Jeddah', locAr: 'جدة', typeEn: 'Full-time', typeAr: 'دوام كامل', grade: 'E4', openings: 1, status: 'open', posted: 5, applicants: 64, mgrEn: 'Tariq Al-Harbi', mgrAr: 'طارق الحربي', salary: '26,000 – 34,000', topStage: 'aiInterview' },
  { id: 'j4', titleEn: 'Financial Analyst', titleAr: 'محلل مالي', deptId: 'fin', locEn: 'Riyadh', locAr: 'الرياض', typeEn: 'Full-time', typeAr: 'دوام كامل', grade: 'E2', openings: 2, status: 'closing', posted: 21, applicants: 98, mgrEn: 'Hanan Al-Dossari', mgrAr: 'حنان الدوسري', salary: '16,000 – 22,000', topStage: 'offer' },
  { id: 'j5', titleEn: 'Growth Marketing Lead', titleAr: 'قائد تسويق النمو', deptId: 'mkt', locEn: 'Dubai', locAr: 'دبي', typeEn: 'Full-time', typeAr: 'دوام كامل', grade: 'M2', openings: 1, status: 'open', posted: 3, applicants: 41, mgrEn: 'Salem Al-Ghamdi', mgrAr: 'سالم الغامدي', salary: '22,000 – 30,000', topStage: 'screening' },
  { id: 'j6', titleEn: 'DevOps Engineer', titleAr: 'مهندس DevOps', deptId: 'eng', locEn: 'Remote – KSA', locAr: 'عن بُعد – السعودية', typeEn: 'Full-time', typeAr: 'دوام كامل', grade: 'E3', openings: 2, status: 'open', posted: 15, applicants: 73, mgrEn: 'Noura Al-Qahtani', mgrAr: 'نورة القحطاني', salary: '20,000 – 28,000', topStage: 'applied' },
  { id: 'j7', titleEn: 'UX Researcher', titleAr: 'باحث تجربة المستخدم', deptId: 'prod', locEn: 'Riyadh', locAr: 'الرياض', typeEn: 'Contract', typeAr: 'عقد', grade: 'E3', openings: 1, status: 'draft', posted: 0, applicants: 0, mgrEn: 'Faisal Al-Otaibi', mgrAr: 'فيصل العتيبي', salary: '18,000 – 24,000', topStage: 'applied' },
  { id: 'j8', titleEn: 'HR Business Partner', titleAr: 'شريك أعمال الموارد البشرية', deptId: 'hr', locEn: 'Dammam', locAr: 'الدمام', typeEn: 'Full-time', typeAr: 'دوام كامل', grade: 'M2', openings: 1, status: 'onhold', posted: 30, applicants: 55, mgrEn: 'Maha Al-Shehri', mgrAr: 'مها الشهري', salary: '19,000 – 26,000', topStage: 'hrInterview' },
]

export const candidates: Candidate[] = [
  {
    id: 'c1', nameEn: 'Abdulrahman Al-Saud', nameAr: 'عبدالرحمن آل سعود', initials: 'ع', avatarColor: C(265),
    titleEn: 'Product Manager · STC Pay', titleAr: 'مدير منتجات · STC Pay',
    jobId: 'j1', stage: 'aiInterview', match: 94, exp: 8, applied: 6,
    locEn: 'Riyadh, KSA', locAr: 'الرياض، السعودية', email: 'a.alsaud@example.com', phone: '+966 50 112 3344',
    eduEn: 'MBA, KFUPM · BSc Computer Science, KSU', eduAr: 'ماجستير إدارة أعمال، جامعة الملك فهد · بكالوريوس علوم حاسب، جامعة الملك سعود',
    skills: ['Product Strategy', 'Fintech', 'Agile', 'Roadmapping', 'SQL', 'Stakeholder Mgmt', 'A/B Testing'],
    missingSkills: ['Mobile growth', 'ML products'],
    langs: [{ en: 'Arabic', ar: 'العربية', lvl: 'Native' }, { en: 'English', ar: 'الإنجليزية', lvl: 'Fluent' }],
    certs: ['Pragmatic PM', 'SAFe PO/PM', 'Google Analytics'],
    factors: { skills: 96, experience: 92, education: 90, industry: 98, certs: 88, language: 95 },
    assess: 91, video: 89, percentile: 96, sourceEn: 'LinkedIn', sourceAr: 'لينكدإن',
    summaryEn: 'Highly recommended candidate with 8 years of fintech product leadership at STC Pay and Geidea. Strong on payments strategy and stakeholder alignment; excellent bilingual communication. Minor gap in ML-driven product experience.',
    summaryAr: 'مرشح يُوصى به بشدة بخبرة 8 سنوات في قيادة منتجات التقنية المالية لدى STC Pay وجيديا. قوي في استراتيجية المدفوعات ومواءمة أصحاب المصلحة؛ تواصل ثنائي اللغة ممتاز. فجوة بسيطة في خبرة منتجات تعلّم الآلة.',
  },
  {
    id: 'c2', nameEn: 'Sara Al-Mutairi', nameAr: 'سارة المطيري', initials: 'س', avatarColor: C(20),
    titleEn: 'Senior PM · Jahez', titleAr: 'مدير منتجات أول · جاهز',
    jobId: 'j1', stage: 'assessment', match: 90, exp: 7, applied: 9,
    locEn: 'Riyadh, KSA', locAr: 'الرياض، السعودية', email: 's.almutairi@example.com', phone: '+966 55 220 7788',
    eduEn: 'BSc Industrial Engineering, KAU', eduAr: 'بكالوريوس هندسة صناعية، جامعة الملك عبدالعزيز',
    skills: ['Product Discovery', 'Marketplaces', 'Data Analysis', 'Figma', 'OKRs', 'User Research'],
    missingSkills: ['Payments', 'B2B SaaS'],
    langs: [{ en: 'Arabic', ar: 'العربية', lvl: 'Native' }, { en: 'English', ar: 'الإنجليزية', lvl: 'Fluent' }],
    certs: ['Reforge PM', 'Scrum PSPO I'],
    factors: { skills: 91, experience: 86, education: 88, industry: 84, certs: 82, language: 94 },
    assess: 88, video: 85, percentile: 91, sourceEn: 'Bayt', sourceAr: 'بيت.كوم',
    summaryEn: 'Strong marketplace PM from Jahez with sharp discovery and analytics skills. Excellent assessment performance. Best suited for consumer-facing roles; lighter on payments domain.',
    summaryAr: 'مديرة منتجات قوية في الأسواق الإلكترونية من جاهز بمهارات اكتشاف وتحليلات ممتازة. أداء تقييم متميّز. الأنسب للأدوار الموجهة للمستهلك؛ خبرة أقل في مجال المدفوعات.',
  },
  {
    id: 'c3', nameEn: 'Omar Khalil', nameAr: 'عمر خليل', initials: 'O', avatarColor: C(150),
    titleEn: 'Product Lead · Careem', titleAr: 'قائد منتجات · كريم',
    jobId: 'j1', stage: 'screening', match: 87, exp: 9, applied: 4,
    locEn: 'Dubai, UAE', locAr: 'دبي، الإمارات', email: 'o.khalil@example.com', phone: '+971 50 661 2200',
    eduEn: 'MSc Computer Science, AUB', eduAr: 'ماجستير علوم حاسب، الجامعة الأمريكية في بيروت',
    skills: ['Platform PM', 'APIs', 'Growth', 'Experimentation', 'SQL', 'Strategy'],
    missingSkills: ['Arabic-first products'],
    langs: [{ en: 'Arabic', ar: 'العربية', lvl: 'Conversational' }, { en: 'English', ar: 'الإنجليزية', lvl: 'Native' }],
    certs: ['Mind the Product', 'AWS CP'],
    factors: { skills: 89, experience: 94, education: 86, industry: 82, certs: 78, language: 80 },
    assess: 0, video: 0, percentile: 84, sourceEn: 'Referral', sourceAr: 'ترشيح',
    summaryEn: 'Seasoned platform PM from Careem with deep growth and experimentation background. Strong technical fluency. Relocation from UAE required; Arabic is conversational.',
    summaryAr: 'مدير منتجات منصات متمرّس من كريم بخلفية عميقة في النمو والتجارب. طلاقة تقنية عالية. يتطلب الانتقال من الإمارات؛ العربية بمستوى محادثة.',
  },
  {
    id: 'c4', nameEn: 'Lina Haddad', nameAr: 'لينا حداد', initials: 'L', avatarColor: C(330),
    titleEn: 'Group PM · Noon', titleAr: 'مدير منتجات مجموعة · نون',
    jobId: 'j1', stage: 'applied', match: 82, exp: 10, applied: 1,
    locEn: 'Riyadh, KSA', locAr: 'الرياض، السعودية', email: 'l.haddad@example.com', phone: '+966 53 778 9911',
    eduEn: 'MBA INSEAD · BSc CS', eduAr: 'ماجستير إدارة أعمال إنسياد · بكالوريوس علوم حاسب',
    skills: ['E-commerce', 'Team Leadership', 'Roadmapping', 'Vision', 'Hiring'],
    missingSkills: ['Hands-on analytics', 'Fintech'],
    langs: [{ en: 'Arabic', ar: 'العربية', lvl: 'Fluent' }, { en: 'English', ar: 'الإنجليزية', lvl: 'Fluent' }],
    certs: ['INSEAD Exec'],
    factors: { skills: 84, experience: 95, education: 92, industry: 80, certs: 70, language: 90 },
    assess: 0, video: 0, percentile: 79, sourceEn: 'Career Portal', sourceAr: 'بوابة التوظيف',
    summaryEn: 'Senior leader with broad e-commerce scope at Noon. Excellent for a people-leadership track. Slightly senior for the IC scope of this requisition.',
    summaryAr: 'قائدة كبيرة بنطاق واسع في التجارة الإلكترونية لدى نون. ممتازة لمسار قيادة الفرق. أقدم قليلاً من نطاق هذه الوظيفة الفردية.',
  },
  {
    id: 'c5', nameEn: 'Yousef Al-Rashid', nameAr: 'يوسف الراشد', initials: 'ي', avatarColor: C(245),
    titleEn: 'Frontend Engineer · Tamara', titleAr: 'مهندس واجهات · تمارا',
    jobId: 'j2', stage: 'techInterview', match: 92, exp: 6, applied: 7,
    locEn: 'Riyadh, KSA', locAr: 'الرياض، السعودية', email: 'y.rashid@example.com', phone: '+966 56 334 1100',
    eduEn: 'BSc Software Engineering, KSU', eduAr: 'بكالوريوس هندسة برمجيات، جامعة الملك سعود',
    skills: ['React', 'TypeScript', 'Next.js', 'Design Systems', 'Performance', 'RTL/i18n', 'Testing'],
    missingSkills: ['Mobile (RN)'],
    langs: [{ en: 'Arabic', ar: 'العربية', lvl: 'Native' }, { en: 'English', ar: 'الإنجليزية', lvl: 'Fluent' }],
    certs: ['Meta Frontend', 'AWS Dev Assoc'],
    factors: { skills: 95, experience: 88, education: 86, industry: 90, certs: 84, language: 92 },
    assess: 94, video: 90, percentile: 95, sourceEn: 'LinkedIn', sourceAr: 'لينكدإن',
    summaryEn: 'Top-tier frontend engineer from Tamara with exceptional React/TypeScript depth and strong RTL/i18n experience — directly relevant to bilingual products. Highest assessment score in the pool.',
    summaryAr: 'مهندس واجهات من الطراز الأول من تمارا بعمق استثنائي في React/TypeScript وخبرة قوية في RTL والتعدد اللغوي — وثيق الصلة بالمنتجات ثنائية اللغة. أعلى نتيجة تقييم في المجموعة.',
  },
  {
    id: 'c6', nameEn: 'Maryam Al-Balushi', nameAr: 'مريم البلوشي', initials: 'م', avatarColor: C(190),
    titleEn: 'Frontend Engineer · Mrsool', titleAr: 'مهندسة واجهات · مرسول',
    jobId: 'j2', stage: 'assessment', match: 86, exp: 5, applied: 5,
    locEn: 'Jeddah, KSA', locAr: 'جدة، السعودية', email: 'm.balushi@example.com', phone: '+966 59 880 6677',
    eduEn: 'BSc Computer Science, Effat University', eduAr: 'بكالوريوس علوم حاسب، جامعة عفت',
    skills: ['React', 'Vue', 'CSS Architecture', 'Accessibility', 'Jest', 'Figma'],
    missingSkills: ['TypeScript depth', 'SSR'],
    langs: [{ en: 'Arabic', ar: 'العربية', lvl: 'Native' }, { en: 'English', ar: 'الإنجليزية', lvl: 'Fluent' }],
    certs: ['Google UX', 'freeCodeCamp'],
    factors: { skills: 88, experience: 80, education: 85, industry: 86, certs: 76, language: 90 },
    assess: 83, video: 0, percentile: 82, sourceEn: 'Indeed', sourceAr: 'إنديد',
    summaryEn: 'Promising frontend engineer with strong accessibility and design sensibility. Solid assessment. Would benefit from deeper TypeScript and SSR exposure for this senior role.',
    summaryAr: 'مهندسة واجهات واعدة بحس قوي في إتاحة الوصول والتصميم. تقييم جيد. ستستفيد من خبرة أعمق في TypeScript والعرض من الخادم لهذا الدور الأول.',
  },
  {
    id: 'c7', nameEn: 'Khalid Al-Anazi', nameAr: 'خالد العنزي', initials: 'خ', avatarColor: C(60),
    titleEn: 'Software Engineer · Lean', titleAr: 'مهندس برمجيات · لين',
    jobId: 'j2', stage: 'screening', match: 79, exp: 4, applied: 3,
    locEn: 'Riyadh, KSA', locAr: 'الرياض، السعودية', email: 'k.anazi@example.com', phone: '+966 50 445 2233',
    eduEn: 'BSc Information Systems, IMSIU', eduAr: 'بكالوريوس نظم معلومات، جامعة الإمام',
    skills: ['JavaScript', 'React', 'Node.js', 'REST', 'Git'],
    missingSkills: ['Design systems', 'Performance', 'TypeScript'],
    langs: [{ en: 'Arabic', ar: 'العربية', lvl: 'Native' }, { en: 'English', ar: 'الإنجليزية', lvl: 'Intermediate' }],
    certs: ['Udacity FE Nanodegree'],
    factors: { skills: 78, experience: 72, education: 82, industry: 80, certs: 68, language: 74 },
    assess: 0, video: 0, percentile: 68, sourceEn: 'Career Portal', sourceAr: 'بوابة التوظيف',
    summaryEn: 'Mid-level engineer with solid fundamentals and fintech exposure at Lean. Below the seniority bar for this requisition but a strong fit for an E3 backfill.',
    summaryAr: 'مهندس متوسط المستوى بأساسيات متينة وخبرة في التقنية المالية لدى لين. أقل من مستوى الأقدمية لهذه الوظيفة لكنه مناسب جداً لشاغر بدرجة E3.',
  },
  {
    id: 'c8', nameEn: 'Aisha Al-Zahrani', nameAr: 'عائشة الزهراني', initials: 'ع', avatarColor: C(295),
    titleEn: 'ML Engineer · Mozn', titleAr: 'مهندسة تعلم آلة · موزن',
    jobId: 'j3', stage: 'aiInterview', match: 93, exp: 6, applied: 4,
    locEn: 'Jeddah, KSA', locAr: 'جدة، السعودية', email: 'a.zahrani@example.com', phone: '+966 54 909 1122',
    eduEn: 'MSc Machine Learning, KAUST', eduAr: 'ماجستير تعلّم الآلة، جامعة الملك عبدالله (كاوست)',
    skills: ['Python', 'PyTorch', 'NLP', 'Arabic NLP', 'MLOps', 'SQL', 'Statistics'],
    missingSkills: ['Large-scale serving'],
    langs: [{ en: 'Arabic', ar: 'العربية', lvl: 'Native' }, { en: 'English', ar: 'الإنجليزية', lvl: 'Fluent' }],
    certs: ['DeepLearning.AI', 'TensorFlow Dev'],
    factors: { skills: 95, experience: 86, education: 96, industry: 90, certs: 90, language: 92 },
    assess: 92, video: 91, percentile: 97, sourceEn: 'Referral', sourceAr: 'ترشيح',
    summaryEn: 'Exceptional ML engineer from KAUST with rare Arabic-NLP specialization — strategically valuable. Outstanding assessment and interview scores. Strongest candidate for the Data Scientist role.',
    summaryAr: 'مهندسة تعلّم آلة استثنائية من كاوست بتخصص نادر في معالجة اللغة العربية — قيمة استراتيجية. نتائج تقييم ومقابلة متميزة. أقوى مرشحة لوظيفة عالم البيانات.',
  },
  {
    id: 'c9', nameEn: 'Hassan Al-Najjar', nameAr: 'حسن النجار', initials: 'ح', avatarColor: C(120),
    titleEn: 'Data Analyst · stc', titleAr: 'محلل بيانات · stc',
    jobId: 'j3', stage: 'applied', match: 80, exp: 5, applied: 2,
    locEn: 'Riyadh, KSA', locAr: 'الرياض، السعودية', email: 'h.najjar@example.com', phone: '+966 57 332 8800',
    eduEn: 'BSc Statistics, KSU', eduAr: 'بكالوريوس إحصاء، جامعة الملك سعود',
    skills: ['SQL', 'Power BI', 'Python', 'ETL', 'A/B Testing'],
    missingSkills: ['Deep learning', 'MLOps', 'Research'],
    langs: [{ en: 'Arabic', ar: 'العربية', lvl: 'Native' }, { en: 'English', ar: 'الإنجليزية', lvl: 'Fluent' }],
    certs: ['Microsoft DA', 'Google Data Analytics'],
    factors: { skills: 80, experience: 78, education: 82, industry: 84, certs: 80, language: 88 },
    assess: 0, video: 0, percentile: 70, sourceEn: 'LinkedIn', sourceAr: 'لينكدإن',
    summaryEn: 'Strong analytics generalist from stc with good BI and SQL. Lighter on ML research depth required for a Data Scientist track.',
    summaryAr: 'محلل بيانات عام قوي من stc بمهارات جيدة في ذكاء الأعمال وSQL. خبرة أقل في عمق أبحاث تعلّم الآلة المطلوبة لمسار عالم البيانات.',
  },
  {
    id: 'c10', nameEn: 'Fatima Al-Shamsi', nameAr: 'فاطمة الشامسي', initials: 'ف', avatarColor: C(10),
    titleEn: 'Senior Financial Analyst · ACWA Power', titleAr: 'محللة مالية أولى · أكوا باور',
    jobId: 'j4', stage: 'offer', match: 91, exp: 7, applied: 18,
    locEn: 'Riyadh, KSA', locAr: 'الرياض، السعودية', email: 'f.shamsi@example.com', phone: '+966 55 667 3322',
    eduEn: 'BSc Finance, KFUPM · CFA Level III', eduAr: 'بكالوريوس مالية، جامعة الملك فهد · CFA المستوى الثالث',
    skills: ['Financial Modeling', 'Valuation', 'IFRS', 'Power BI', 'Forecasting', 'M&A'],
    missingSkills: ['Treasury'],
    langs: [{ en: 'Arabic', ar: 'العربية', lvl: 'Native' }, { en: 'English', ar: 'الإنجليزية', lvl: 'Fluent' }],
    certs: ['CFA III Candidate', 'FMVA'],
    factors: { skills: 93, experience: 90, education: 92, industry: 94, certs: 95, language: 90 },
    assess: 90, video: 88, percentile: 94, sourceEn: 'Referral', sourceAr: 'ترشيح',
    summaryEn: 'Excellent finance candidate from ACWA Power with strong modeling and IFRS depth and CFA progress. Cleared all interviews — offer in progress.',
    summaryAr: 'مرشحة مالية ممتازة من أكوا باور بعمق قوي في النمذجة ومعايير IFRS وتقدم في CFA. اجتازت جميع المقابلات — العرض قيد الإعداد.',
  },
  {
    id: 'c11', nameEn: 'Mohammed Al-Dosari', nameAr: 'محمد الدوسري', initials: 'م', avatarColor: C(85),
    titleEn: 'Performance Marketer · Hungerstation', titleAr: 'مسوّق أداء · هنقرستيشن',
    jobId: 'j5', stage: 'screening', match: 84, exp: 6, applied: 2,
    locEn: 'Dubai, UAE', locAr: 'دبي، الإمارات', email: 'm.dosari@example.com', phone: '+971 52 778 9090',
    eduEn: 'BBA Marketing, GUST', eduAr: 'بكالوريوس إدارة أعمال تسويق، جامعة الخليج',
    skills: ['Paid Social', 'SEO', 'CRM', 'Analytics', 'Growth Loops', 'Arabic copy'],
    missingSkills: ['Brand', 'B2B'],
    langs: [{ en: 'Arabic', ar: 'العربية', lvl: 'Native' }, { en: 'English', ar: 'الإنجليزية', lvl: 'Fluent' }],
    certs: ['Google Ads', 'Meta Blueprint'],
    factors: { skills: 86, experience: 82, education: 80, industry: 88, certs: 84, language: 90 },
    assess: 0, video: 0, percentile: 78, sourceEn: 'LinkedIn', sourceAr: 'لينكدإن',
    summaryEn: 'Performance-focused growth marketer with strong paid acquisition track record at Hungerstation. Solid bilingual copy. Less brand/B2B exposure.',
    summaryAr: 'مسوّق نمو يركز على الأداء بسجل قوي في الاستحواذ المدفوع لدى هنقرستيشن. كتابة ثنائية اللغة جيدة. خبرة أقل في العلامة التجارية وقطاع B2B.',
  },
]

export const stages = [
  { id: 'applied', color: 'var(--text-3)' },
  { id: 'screening', color: 'var(--info)' },
  { id: 'assessment', color: 'var(--purple)' },
  { id: 'aiInterview', color: 'var(--ai)' },
  { id: 'hrInterview', color: 'var(--accent)' },
  { id: 'techInterview', color: 'var(--accent)' },
  { id: 'offer', color: 'var(--warning)' },
  { id: 'hired', color: 'var(--success)' },
]

export const employmentTypes = [
  { en: 'Full-time', ar: 'دوام كامل' }, { en: 'Part-time', ar: 'دوام جزئي' },
  { en: 'Contract', ar: 'عقد' }, { en: 'Internship', ar: 'تدريب' },
]

export const grades = ['E2', 'E3', 'E4', 'M2', 'M3', 'M4']

export const locations = [
  { en: 'Riyadh', ar: 'الرياض' }, { en: 'Jeddah', ar: 'جدة' }, { en: 'Dammam', ar: 'الدمام' },
  { en: 'Dubai', ar: 'دبي' }, { en: 'Remote – KSA', ar: 'عن بُعد – السعودية' },
]

export const users = [
  { id: 'u1', nameEn: 'Layla Al-Fayez', nameAr: 'ليلى الفايز', email: 'l.alfayez@connect.ai', role: 'admin', status: 'active', jobCount: 12, lastActiveEn: 'Now', lastActiveAr: 'الآن', initials: 'ل', avatarColor: C(300) },
  { id: 'u2', nameEn: 'Rawan Al-Otaibi', nameAr: 'روان العتيبي', email: 'r.alotaibi@connect.ai', role: 'recruiter', status: 'active', jobCount: 6, lastActiveEn: '2h ago', lastActiveAr: 'منذ ساعتين', initials: 'ر', avatarColor: C(170) },
  { id: 'u3', nameEn: 'Faisal Al-Otaibi', nameAr: 'فيصل العتيبي', email: 'f.alotaibi@connect.ai', role: 'hm', status: 'active', jobCount: 3, lastActiveEn: 'Yesterday', lastActiveAr: 'أمس', initials: 'ف', avatarColor: C(40) },
  { id: 'u4', nameEn: 'Noura Al-Qahtani', nameAr: 'نورة القحطاني', email: 'n.alqahtani@connect.ai', role: 'hm', status: 'active', jobCount: 4, lastActiveEn: '3d ago', lastActiveAr: 'قبل 3 أيام', initials: 'ن', avatarColor: C(220) },
  { id: 'u5', nameEn: 'Tariq Al-Harbi', nameAr: 'طارق الحربي', email: 't.alharbi@connect.ai', role: 'interviewer', status: 'active', jobCount: 2, lastActiveEn: '1w ago', lastActiveAr: 'قبل أسبوع', initials: 'ط', avatarColor: C(90) },
  { id: 'u6', nameEn: 'Sara Ahmad', nameAr: 'سارة أحمد', email: 's.ahmad@connect.ai', role: 'external', status: 'pending', jobCount: 0, lastActiveEn: '—', lastActiveAr: '—', initials: 'س', avatarColor: C(0) },
  { id: 'u7', nameEn: 'Maha Al-Shehri', nameAr: 'مها الشهري', email: 'm.alshehri@connect.ai', role: 'recruiter', status: 'suspended', jobCount: 0, lastActiveEn: '2w ago', lastActiveAr: 'قبل أسبوعين', initials: 'م', avatarColor: C(130) },
]
